imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SiaBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es_MX

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

vich_uploader:
    db_driver: orm

    mappings:
        sia_cartaInvitacion:
            uri_prefix:         /SIA2/submissions
            delete_on_remove: true
            delete_on_update: true
            upload_destination: %kernel.root_dir%/../web/submissions
            namer:              vich_uploader.namer_uniqid

        sia_cartaSolicitud:
            uri_prefix:         /SIA2/submissions
            delete_on_remove: true
            delete_on_update: true
            upload_destination: %kernel.root_dir%/../web/submissions
            namer:              vich_uploader.namer_uniqid

        sia_plan:
            uri_prefix:         /SIA2/submissions
            delete_on_remove: true
            delete_on_update: true
            upload_destination: %kernel.root_dir%/../web/submissions
            namer:              vich_uploader.namer_uniqid

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SiaBundle\Entity\User
    from_email:
            address:        webmaster@matmor.unam.mx
            sender_name:    Centro de Ciencias Matemáticas

stof_doctrine_extensions:
    default_locale: es_MX
    orm:
        default:
            timestampable: true
            sluggable: true
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
             - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.date:
            class: Twig_Extensions_Extension_Date
            tags:
                - { name: twig.extension }