# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    Ccm.form.flow.createSolicitud:
        class: SiaBundle\Form\CreateSolicitudFlow
        parent: craue.form.flow
#        scope: request
#        calls:
#            - [ setFormType, [ "@Ccm.form.create_vehicle" ] ]

    Ccm.form.flow.createActividad:
        class: SiaBundle\Form\CreateActividadFlow
        parent: craue.form.flow
#        scope: request
#        calls:
#            - [ setFormType, [ "@Ccm.form.create_vehicle" ] ]

    app.inves_voter:
        class: SiaBundle\Security\InvesVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
        # small performance boost



