# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    Ccm.form.flow.createSolicitud:
        class: SiaBundle\Form\CreateSolicitudFlow
        parent: craue.form.flow
#        scope: request
#        calls:
#            - [ setFormType, [ "@Ccm.form.create_vehicle" ] ]

    Ccm.form.flow.createActividad:
        class: SiaBundle\Form\CreateActividadFlow
        parent: craue.form.flow
#        scope: request
#        calls:
#            - [ setFormType, [ "@Ccm.form.create_vehicle" ] ]

    Ccm.form.flow.createActividadVisitante:
        class: SiaBundle\Form\CreateActividadVisitanteFlow
        parent: craue.form.flow
#        scope: request
#        calls:
#            - [ setFormType, [ "@Ccm.form.create_vehicle" ] ]

    app.inves_voter:
        class: SiaBundle\Security\SiaVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
        # small performance boost

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    app.recomendacion:
        class:     SiaBundle\Service\Recomendacion
        arguments: [@doctrine.orm.entity_manager]