<?php

namespace SiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicoRepository extends EntityRepository
{
    /**
     * Change default sort order for entities
     * Sorted by name ascending.
     *
     * @return array of entities:
     */
    public function findAll()
    {
        return $this->findBy(array(), array('apellido' => 'ASC'));
    }
}
