<?php

namespace SiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicoRepository extends EntityRepository
{
    /**
     * Change default sort order for entities
     * Sorted by name ascending.
     *
     * @return array of entities:
     */
    public function findAll()
    {
        return $this->findBy(array(), array('apellido' => 'ASC'));
    }

    public function findAllOrderedByApellido()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM SiaBundle:Academico a ORDER BY a.apellido ASC'
            )
            ->getResult();
    }

    public function findByAcademico($academico_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM SiaBundle:Solicitud s
                    JOIN s.academico a
                    WHERE a.id = :id
                    ORDER BY s.tipo ASC, s.fechaInicio ASC"
            )
            ->setParameter('id', $academico_id)
            ->getResult();
    }


}
