<?php

namespace SiaBundle\Repository;

/**
 * AsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
