<?php

namespace SiaBundle\Repository;

/**
 * ComplementariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplementariaRepository extends \Doctrine\ORM\EntityRepository
{
}
