<?php

namespace SiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SesionRepository extends EntityRepository
{

    public function findProxSesion($fechaSolicitud)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Sesion s
                     WHERE s.fecha > :fechaSolicitud
                ORDER BY s.fecha ASC '
            )
            ->setParameter('fechaSolicitud', $fechaSolicitud)
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function findSolicitudes($tipo, $sesion)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM SiaBundle:Solicitud s
                  JOIN s.sesion se
                  WHERE s.tipo = :tipo AND se = :sesion 
                  ORDER BY s.fechaInicio ASC"
            )
            ->setParameter('tipo', $tipo)
            ->setParameter('sesion', $sesion)
            ->getResult();
    }

    public function findAllSolicitudes($sesion)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM SiaBundle:Solicitud s
                  JOIN s.sesion se
                  WHERE s.tipo = :tipo  
                  ORDER BY s.fechaInicio ASC"
            )
            ->setParameter('sesion', $sesion)
            ->getResult();
    }


}
