<?php

namespace SiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SesionRepository extends EntityRepository
{

    public function findProxSesion($fechaSolicitud)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Sesion s
                     WHERE s.fecha >= :fechaSolicitud
                ORDER BY s.fecha DESC'
            )
            ->setParameter('fechaSolicitud', $fechaSolicitud)
            ->setMaxResults(1)
            ->getSingleResult();
    }

}
