<?php

namespace SiaBundle\Repository;

use SiaBundle\Entity\Academico;
use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{

    public function findAllByYear(Academico $academico, $year)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s 
                     WHERE SUBSTRING(s.fechaInicio,1,4) >= :year AND s.academico = :id
                         ORDER BY s.created ASC, ORDER BY s.id ASC'
            )
            ->setParameter('id', $academico->getId())
            ->setParameter('year', $year)
            ->getResult();
    }

    public function findAllNew()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s
                     WHERE s.enviada = TRUE
                     AND s.sesion IS NULL
                ORDER BY s.created ASC'
            )

            ->getResult();
    }

    public function findPending()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s
                     WHERE s.enviada IS NULL
                     OR s.dictamen IS NULL
                     or s.sesion IS NULL
                ORDER BY s.created ASC'
            )
            ->getResult();
    }

    public function findVisitantes()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM SiaBundle:Solicitud s
                  WHERE s.tipo = :tipo AND SUBSTRING(s.fechaInicio,1,4) = :year 
                  ORDER BY s.fechaInicio ASC, ORDER BY s.id ASC"
            )
            ->setParameter('tipo', 'Visitante')
            ->setParameter('year', '2018')
            ->getResult();
    }

    public function findEventos($tipo)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a FROM SiaBundle:Actividad a
                  JOIN a.solicitud s 
                  WHERE a.tipo = :tipo AND SUBSTRING(s.fechaInicio,1,4) = :year 
                  ORDER BY s.fechaInicio ASC"
            )
            ->setParameter('tipo', $tipo)
            ->setParameter('year', '2018')
            ->getResult();
    }

}
