<?php

namespace SiaBundle\Repository;

use SiaBundle\Entity\Academico;
use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{

    public function findAllByYear(Academico $academico, $year)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s 
                     WHERE SUBSTRING(s.fechaInicio,1,4) = :year AND s.academico = :id
                         ORDER BY s.created ASC'
            )
            ->setParameter('id', $academico->getId())
            ->setParameter('year', $year)
            ->getResult();
    }

    public function findAllNew()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s
                     WHERE s.enviada = TRUE
                     AND s.sesion IS NULL
                ORDER BY s.created ASC'
            )

            ->getResult();
    }

    public function findPending()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM SiaBundle:Solicitud s
                     WHERE s.enviada IS NULL
                     OR s.dictamen IS NULL
                     or s.sesion IS NULL
                ORDER BY s.created ASC'
            )

            ->getResult();
    }

}
